#!/bin/bash -e
set -o pipefail

top=$(git rev-parse --show-toplevel)
status=0
while read -r file; do
    if [ ! -f "$file" ]; then
        echo "$file does not exist. Please ensure an Apache 2.0 license is present."
        status=1
    else
        if ! diff -Buw "$top/LICENSE" "$file"; then
            echo
            echo "$file does not match $top/LICENSE!"
            echo
            status=1
        fi
    fi
done < <(find "$top" -name Cargo.toml | sed 's|/Cargo.toml$|/LICENSE|')
exit $status
