#!/bin/bash -e
set -o pipefail

top=$(git rev-parse --show-toplevel)
status=0
while read -r file; do
    if [[ $(tail -c 1 "$file") ]]; then
        echo "$file does not have a newline at EOF. Please ensure it has one."
        status=1
    fi
done < <(find "$top" -path "$top"/target -prune -o -type f -name "*.rs" -print -o -type f -name "*.toml" -print)
exit $status
