version: 2
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.unlabeled, pull_request.synchronize
    validate:
      - do: title
        must_exclude:
          regex: "The IT Crowd"
    fail:
      - do: checks
        status: 'success'
    error:
      - do: checks
        status: 'success'
