[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
	"bounds",
	"crt0stack",
	"enarx-keep",
	"enarx-keep-sev",
	"enarx-keep-sev-shim",
	"enarx-keep-sgx",
	"enarx-keep-sgx-shim",
	"enumerate",
	"integration-tests",
	"intel-types",
	"iocuddle",
	"iocuddle-sgx",
	"keep-runtime",
	"loader",
	"memory",
	"sallyport",
	"sev",
	"sev-show",
	"sevctl",
	"sgx-crypto",
	"sgx-types",
	"testing",
	"units",
	"vdso"
]
ENARX_TEST_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.tests"

[tasks.deny]
command = "cargo"
args = ["deny", "check", "licenses"]

[tasks.misc-lints-missing-docs]
command = "${ENARX_TEST_DIR}/misc-lints-missing-docs"

[tasks.cargo-toml-package-edition]
install_crate = { crate_name = "toml-cli", binary = "toml", test_arg = "--help" }
command = "${ENARX_TEST_DIR}/cargo-toml-package-edition"

[tasks.misc-lints-clippy-all]
command = "${ENARX_TEST_DIR}/misc-lints-clippy-all"

[tasks.misc-licenses-rs-spdx]
command = "${ENARX_TEST_DIR}/misc-licenses-rs-spdx"

[tasks.misc-licenses-asm-spdx]
command = "${ENARX_TEST_DIR}/misc-licenses-asm-spdx"

[tasks.misc-diagrams]
workspace = false
# This is the only non-crate-level task. To prevent the pre-ci-flow
# from spuriously triggering this *inside* member crates, let's just
# detect whether we're in a crate directory and if we are, this test
# will be skipped. It doesn't make sense to run inside a crate directory.
condition = { env_not_set = ["CARGO_MAKE_CRATE_NAME"]}
command = "${ENARX_TEST_DIR}/misc-diagrams"

[tasks.cargo-toml-package-license]
command = "${ENARX_TEST_DIR}/cargo-toml-package-license"

[tasks.misc-licenses-crate]
command = "${ENARX_TEST_DIR}/misc-licenses-crate"

[tasks.integration]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = "integration-tests" }
run_task = { name = "integration-test", fork = true }

[tasks.integration-test]
command = "cargo"
args = ["test"]

[tasks.integration-ci]
workspace = false
run_task = [
    { name = ["ci-flow", "integration"], fork = true },
]

# Add additional tests to the predefined 'ci-flow' target.
[tasks.pre-ci-flow]
dependencies = [
	"cargo-toml-package-edition",
	"cargo-toml-package-license",
	"check-format",
	"deny",
	"misc-diagrams",
	"misc-licenses-asm-spdx",
	"misc-licenses-crate",
	"misc-licenses-rs-spdx",
	"misc-lints-clippy-all",
	"misc-lints-missing-docs",
]
