#!/bin/bash -e
set -o pipefail

status=0
if [ "$(toml get "Cargo.toml" package.edition)" != '"2018"' ]; then
	echo "$PWD is not using edition = \"2018\"."
	echo "Please ensure the field is present and includes the correct Rust edition."
	status=1
fi
exit $status
