#!/bin/bash -e
set -o pipefail

top=$(git rev-parse --show-toplevel)
status=0
while read -r file; do
    [ "$(toml get "$file" package)" == "null" ] && continue

    if [ "$(toml get "$file" package.license)" != "\"Apache-2.0\"" ]; then
        echo "$file does not include Apache-2.0 in its license field."
        echo "Please ensure the field is present and includes an Apache license."
        status=1
    fi
done < <(find "$top" -name Cargo.toml)
exit $status
