#!/bin/bash -e
set -o pipefail

status=0
if [ "$(toml get "Cargo.toml" package.license)" != "\"Apache-2.0\"" ]; then
	echo "$PWD/Cargo.toml does not include Apache-2.0 in its license field."
	echo "Please ensure the field is present and includes an Apache license."
	status=1
fi
exit $status
