[package]
name = "vdso"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dev-dependencies]
libc = "0.2.67"

[dependencies]
crt0stack = { path = "../crt0stack" }
goblin = "0.2.0"
