#!/bin/bash -e
top=`git rev-parse --show-toplevel`
status=0
for file in $(find "$top" -name Cargo.toml); do
    if [ "$(toml get "$file" package.edition)" != '"2018"' ]; then
        echo "$file is not using edition = "2018"."
        echo "Please ensure the field is present and includes the correct Rust edition."        
        status=1
    fi
done
exit $status
