[package]
name = "enarx-keep"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enarx-keep-sev-shim = { path = "../enarx-keep-sev-shim" }
sallyport = { path = "../sallyport" }
sgx = { path = "../sgx", default-features = false }
bounds = { path = "../bounds" }
memory = { path = "../memory" }
mmap = { path = "../mmap" }
units = { path = "../units" }
kvm-bindings = "0.3.0"
kvm-ioctls = "0.5.0"
structopt = "0.3"
colorful = "0.2"
goblin = "0.2"
libc = "0.2"
x86_64 = { version = "0.11.0", default-features = false, features = ["stable"] }
