// SPDX-License-Identifier: Apache-2.0

//! Generated with:
//! ```console
//! $ curl https://raw.githubusercontent.com/xen-project/xen/master/xen/include/public/arch-x86/hvm/start_info.h > start_info.h
//! $ bindgen --use-core \
//!   --whitelist-var 'XEN_HVM_MEMMAP_TYPE_.*' \
//!   --whitelist-type hvm_start_info \
//!   --whitelist-type hvm_modlist_entry \
//!   --whitelist-type hvm_memmap_table_entry \
//!   --whitelist-var XEN_HVM_START_MAGIC_VALUE start_info.h \
//!   --blacklist-type '__uint.*' \
//!   --no-layout-tests \
//!   -- -include "/usr/include/stdint.h"
//! ```

/* automatically generated by rust-bindgen */

pub const XEN_HVM_START_MAGIC_VALUE: u32 = 862897528;
pub const XEN_HVM_MEMMAP_TYPE_RAM: u32 = 1;
pub const XEN_HVM_MEMMAP_TYPE_RESERVED: u32 = 2;
pub const XEN_HVM_MEMMAP_TYPE_ACPI: u32 = 3;
pub const XEN_HVM_MEMMAP_TYPE_NVS: u32 = 4;
pub const XEN_HVM_MEMMAP_TYPE_UNUSABLE: u32 = 5;
pub const XEN_HVM_MEMMAP_TYPE_DISABLED: u32 = 6;
pub const XEN_HVM_MEMMAP_TYPE_PMEM: u32 = 7;
#[repr(C)]
pub struct hvm_start_info {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub nr_modules: u32,
    pub modlist_paddr: u64,
    pub cmdline_paddr: u64,
    pub rsdp_paddr: u64,
    pub memmap_paddr: u64,
    pub memmap_entries: u32,
    pub reserved: u32,
}
#[repr(C)]
pub struct hvm_modlist_entry {
    pub paddr: u64,
    pub size: u64,
    pub cmdline_paddr: u64,
    pub reserved: u64,
}
#[repr(C)]
pub struct hvm_memmap_table_entry {
    pub addr: u64,
    pub size: u64,
    pub type_: u32,
    pub reserved: u32,
}
