[package]
name = "keep-runtime"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-workload = { path = "../keep-libruntime" }

env_logger = "0.7"
log = "0.4"
