[package]
name = "wasmldr"
version = "0.1.0"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"
description = "Enarx WebAssembly Loader"
readme = "README.md"

# TODO: merge these into the toplevel actions/gitignore
exclude = [ ".gitignore", ".github/*" ]

[features]
gdb = []
dbg = []

[dependencies]
wasmtime = { version = "0.32", default-features = false, features = ["cranelift"] }
wasmtime-wasi = { version = "0.32", default-features = false, features = ["sync"] }
wasi-common = { version = "0.32", default-features = false }
wasmparser = "0.81.0"
structopt = { version = "0.3", default-features = false }
anyhow = "1.0"
env_logger = { version = "0.9", default-features = false }
log = "0.4"

[dev-dependencies]
wat = "1.0"

[profile.release]
incremental = false
codegen-units = 1
panic = "abort"
lto = true
debug = 1
opt-level = "s"

[patch.crates-io]
rustix = { git = "https://github.com/haraldh/rustix", branch = "v0.26.2_asm_stable" }
