[package]
name = "wasmldr"
version = "0.2.1"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"
description = "Enarx WebAssembly Loader"
readme = "README.md"

# TODO: merge these into the toplevel actions/gitignore
exclude = [ ".gitignore", ".github/*" ]

[features]
gdb = []
dbg = []

[dependencies]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", branch = "main", default-features = false, features = ["cranelift", "pooling-allocator"] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", branch = "main", default-features = false, features = ["sync"] }
wasi-common = { git = "https://github.com/bytecodealliance/wasmtime", branch = "main", default-features = false }
wiggle = { git = "https://github.com/bytecodealliance/wasmtime", branch = "main", default-features = false }
io-lifetimes = { version = "0.5.0", default-features = false }
cap-std = "0.24.1"
wasmparser = "0.83.0"
anyhow = "1.0"
env_logger = { version = "0.9", default-features = false }
log = "0.4"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
rustls = "0.20.4"
rustls-pemfile = "0.3.0"
webpki-roots = "0.22.2"
x509 = { git = "https://github.com/npmccallum/formats", branch = "steward", features = ["std"] }
pkcs8 = { git = "https://github.com/npmccallum/formats", branch = "steward" }
sec1 = { git = "https://github.com/npmccallum/formats", branch = "steward" }
const-oid = { git = "https://github.com/npmccallum/formats", branch = "steward" }
zeroize = { version = "^1.5.2", features = ["alloc"] }
ring = { version = "0.16.20", features = ["std"] }
ureq = { version = "^2.4.0" }
clap = { version = "3.1.6", default-features = false, features = ["derive", "std"] }
rustix = "0.33.4"

[dev-dependencies]
wat = "1.0"

[profile.release]
incremental = false
codegen-units = 1
panic = "abort"
lto = true
debug = 1
opt-level = "s"
