[package]
name = "wasmldr"
version = "0.1.0"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"
description = "Enarx WebAssembly Loader"
readme = "README.md"

# TODO: merge these into the toplevel actions/gitignore
exclude = [ ".gitignore", ".github/*" ]

[features]
gdb = []
dbg = []

[dependencies]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime.git", rev="853a025613e012c6c29002ddcccfced67073a8d0", default-features = false, features = ["cranelift", "pooling-allocator"] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime.git", rev="853a025613e012c6c29002ddcccfced67073a8d0", default-features = false, features = ["sync"] }
wasi-common = { git = "https://github.com/bytecodealliance/wasmtime.git", rev="853a025613e012c6c29002ddcccfced67073a8d0", default-features = false }
wasmparser = "0.81.0"
structopt = { version = "0.3", default-features = false }
anyhow = "1.0"
env_logger = { version = "0.9", default-features = false }
log = "0.4"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
wat = "1.0"

[profile.release]
incremental = false
codegen-units = 1
panic = "abort"
lto = true
debug = 1
opt-level = "s"
