[package]
name = "linux-errno"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "Apache-2.0"
edition = "2018"

categories = [
    "no-std",
]

keywords = [
    "linux",
    "errno",
    "no_std",
]

[dependencies]
