[package]
name = "enarx-shim-sgx"
version = "0.6.3"
edition = "2021"
description = "Enarx SGX shim"
authors = ["The Enarx Project Developers"]
repository = "https://github.com/enarx/sallyport"
license = "Apache-2.0"

[features]
gdb = ["dep:gdbstub", "dep:gdbstub_arch", "dbg"]
dbg = []
disable-sgx-attestation = []

[dependencies]
bitflags = { version = "1.2", default-features = false }
const-default = { version = "1.0", default-features = false }
crt0stack = { version = "0.1", default-features = false }
goblin = { version = "0.5", features = ["elf64"], default-features = false }
mmledger = { version = "0.3.0", default-features = false }
noted = { version = "1.0.0", default-features = false }
primordial = { version = "0.5.0", features = ["const-default"], default-features = false }
rcrt1 = { version = "2.4.0", default-features = false }
sallyport = { version = "0.6.3", path = "../sallyport", default-features = false }
sgx = { version = "0.5.0", default-features = false }
spinning = { version = "0.1", default-features = false }
x86_64 = { version = "0.14.9", default-features = false }
xsave = { version = "2.0.2", default-features = false }

# optional dependencies
gdbstub = { version = "0.5.0", optional = true, default-features = false }
gdbstub_arch = { version = "0.1.1", optional = true, default-features = false }

[[bin]]
name = "enarx-shim-sgx"
test = false
