[package]
name = "wasmldr"
version = "0.3.0"
authors = ["The Enarx Project Developers"]
edition = "2021"
license = "Apache-2.0"
description = "Enarx WebAssembly Loader"
readme = "README.md"

# TODO: merge these into the toplevel actions/gitignore
exclude = [ ".gitignore", ".github/*" ]

[features]
gdb = []
dbg = []

[dependencies]
wasmtime = { version = "0.35.1", default-features = false, features = ["cranelift", "pooling-allocator"] }
wasmtime-wasi = { version = "0.35.0", default-features = false, features = ["sync"] }
wasi-common = { version = "0.35.0", default-features = false }
wiggle = { version = "0.35.0", default-features = false }
io-lifetimes = { version = "0.6.0", default-features = false }
cap-std = "0.24.2"
system-interface = { version = "0.20.0", features = ["cap_std_impls"] }
wasmparser = "0.83.0"
anyhow = "1.0"
env_logger = { version = "0.9", default-features = false }
log = "0.4"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
rustls = "0.20.4"
rustls-pemfile = "0.3.0"
webpki-roots = "0.22.2"
x509 = { version = "0.0.2", features = ["std"], package = "x509-cert" }
pkcs8 = "0.9.0-pre.1"
sec1 = "0.3.0-pre.1"
const-oid = "0.9.0"
zeroize = { version = "^1.5.4", features = ["alloc"] }
ring = { version = "0.16.20", features = ["std"] }
ureq = { version = "^2.4.0" }
clap = { version = "3.1.6", default-features = false, features = ["derive", "std"] }
rustix = "0.34.0"
url = { version = "2.2.2", features = ["serde"] }
sha2 = "^0.10.2"

[dev-dependencies]
wat = "1.0"
