[package]
name = "sev_attestation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sallyport = "0.1"

[dev-dependencies]
memoffset = "0.6.4"
