[package]
name = "shim-sev"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
sallyport = { path = "../../../sallyport", default-features = false }
rcrt1 = { path = "../../../rcrt1" }
memoffset = { git = "https://github.com/Gilnaa/memoffset", features = ["unstable_const", "unstable_raw"] }
x86_64 = { version = "0.11.2", default-features = false, features = ["array-init", "inline_asm"] }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
goblin = { version = "0.2", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
spinning = { version = "0.0", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.1"
nbytes = "0.1"
lset = "0.1"

[profile.dev.package.rcrt1]
opt-level = 3

[build-dependencies]
cc = "1.0"
walkdir = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
