name: Enarx Standard Tests
# Automated testing run on all commits.

on: [pull_request]

jobs:
  # Ensure the testing infrastructure is working as intended.
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sanity-check test
      run: true

  # Enforce correct fields in Cargo.toml files.
  cargo-toml-tests:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    # Ensure Cargo edition is correct.
    - name: Cargo edition
      run: .tests/cargo-edition

    # Ensure Cargo.toml's license field is Apache 2.0.
    - name: License field
      run: .tests/toml-license-field
