name: Enarx Licensing Tests
# Checks that ensure Enarx's licensing is consistent and correct.

on: [pull_request]

jobs:
  # Enforce correct license files and headers.
  licenses:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    # Ensure that all crates have a top-level Apache 2.0 license.
    - name: Crate-level license test
      run: .tests/crate-license

    # Ensure all .rs files have an Apache 2.0 SPDX license ID.
    - name: SPDX IDs in all .rs files
      run: .tests/rs-spdx-license

    # Ensure Cargo.toml's license field is Apache 2.0.
    - name: Cargo.toml license field
      run: .tests/toml-license-field
