name: Enarx Standard Tests
# Automated testing run on all commits.

on: [pull_request]

jobs:
  # Ensure the testing infrastructure is working as intended.
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sanity-check test
      run: true

  # Enforce correct fields in Cargo.toml files.
  cargo-toml-tests:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    # Ensure Cargo edition is correct.
    - name: Cargo edition
      run: .tests/cargo-edition

  # Miscellaneous organizational tests.
  misc-organization:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
  
    # Ensure all code-related files have a newline at end of file.
    - name: Cargo edition
      run: .tests/eof-newline
