name: misc

on: [pull_request]

jobs:
  # Miscellaneous organizational tests.
  # Enforce correct license files and headers.
  misc-licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Ensure that all crates have a top-level Apache 2.0 license.
    - name: Crate-level licenses present
      run: .tests/misc-licenses-crate

    # Ensure all .rs files have an Apache 2.0 SPDX license ID.
    - name: All .rs files have SPDX IDs
      run: .tests/misc-licenses-rs-spdx

    # Ensure all .s and .S files have an Apache 2.0 SPDX license ID.
    - name: All .s/.S files have SPDX IDs
      run: .tests/misc-licenses-asm-spdx
      
  misc-diagrams:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Ensure all diagrams are up-to-date.
    - name: All diagrams are up-to-date
      run: .tests/misc-diagrams
