name: misc

on: [pull_request]

jobs:
  misc-consistent-linked-issues:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora
    steps:
    - uses: actions/checkout@v2
    
    # Ensure issues mentioned in commits are also present in the PR description
    # and properly linked.
    - name: Linked issues are consistent between commits and PR description
      run: .tests/misc-consistent-linked-issues ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
