name: packet

on: [pull_request]

jobs:
  # Run the CI suite on each technology
  cargo-make-integration-sev:
    runs-on: [self-hosted, linux, sev]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: deep-ci
  cargo-make-integration-sgx1:
    runs-on: [self-hosted, linux, sgx1]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: deep-ci
