name: pr
on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: auto-merge
      id: auto-merge
      run: gh pr merge --auto --rebase $PR_URL
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}

