name: pr
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - name: auto-merge
      id: auto-merge
      run: gh pr merge --auto --rebase $PR_URL
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}

