name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v18
        with:
          nix_conf: experimental-features = nix-command flakes
      - uses: jessestricker/nix-flake-update@v1
        id: nix-update
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: nix-update
          commit-message: ${{ steps.nix-update.outputs.commit-message }}
          title: ${{ steps.nix-update.outputs.pull-request-title }}
          body: ${{ steps.nix-update.outputs.pull-request-body }}
          labels: dependencies, nix
          assignees: |
            rvolosatovs
          signoff: true
